POST http://localhost.localstack.cloud:4000/patients
Content-Type: application/json

{
  "name": "Idris",
  "email": "idris@test.com",
  "address": "123 İstanbul",
  "dateOfBirth": "1900-01-01",
  "registeredDate": "2025-07-22"
}